#网易云合伙人签到
name: wangyiqiandaoBot

on:               
  schedule:                              # 设置定时任务
    - cron: '5 16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2           # 拉取最新的代码
    - name: Set up Python 3.7.6
      uses: actions/setup-python@v2       # 设置 python 版本
      with:
        python-version: 3.7.6
    - name: Install dependencies          # 安装依赖
      run: |
        cd qdrobot
        pip install -r requirements.txt
    - name: start qiandao                      
      run: |
        cd qdrobot
        python copartner.py
